.TH wxColourPickerCtrl 3 "wx 1.9.1" "" "Erlang Module Definition"
.SH NAME
wxColourPickerCtrl \- See external documentation: wxColourPickerCtrl.
.SH DESCRIPTION
.LP
See external documentation: wxColourPickerCtrl\&.
.LP
This class is derived (and can use functions) from: 
.br
wxPickerBase 
.br
wxControl 
.br
wxWindow 
.br
wxEvtHandler 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxColourPickerCtrl():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxColourPickerCtrl()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Parent, Id) -> wxColourPickerCtrl()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
Equivalent to new(Parent, Id, [])\&.
.RE
.LP
.B
new(Parent, Id, Options::[Option]) -> wxColourPickerCtrl()
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
Option = {col, wx:wx_colour()} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx:wx_object()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
create(This, Parent, Id) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
Equivalent to create(This, Parent, Id, [])\&.
.RE
.LP
.B
create(This, Parent, Id, Options::[Option]) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
Option = {col, wx:wx_colour()} | {pos, {X::integer(), Y::integer()}} | {size, {W::integer(), H::integer()}} | {style, integer()} | {validator, wx:wx_object()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getColour(This) -> wx:wx_colour4()
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, Text) -> boolean()
.br
.B
setColour(This, Col) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Text = unicode:chardata()
.br
This = wxColourPickerCtrl()
.br
Col = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
See external documentation\&. 
.br
Also:
.br
setColour(This, Col) -> \&'ok\&' when
.br
This::wxColourPickerCtrl(), Col::wx:wx_colour()\&.
.br

.RE
.LP
.B
destroy(This::wxColourPickerCtrl()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>