.TH wxDisplay 3 "wx 1.9.1" "" "Erlang Module Definition"
.SH NAME
wxDisplay \- See external documentation: wxDisplay.
.SH DESCRIPTION
.LP
See external documentation: wxDisplay\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxDisplay():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxDisplay()
.br
.RS
.LP
Equivalent to new([])\&.
.RE
.LP
.B
new(Options::[Option]) -> wxDisplay()
.br
.RS
.LP
Types:

.RS 3
Option = {n, integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isOk(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getClientArea(This) -> {X::integer(), Y::integer(), W::integer(), H::integer()}
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getGeometry(This) -> {X::integer(), Y::integer(), W::integer(), H::integer()}
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getName(This) -> unicode:charlist()
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
isPrimary(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getCount() -> integer()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFromPoint(Pt) -> integer()
.br
.RS
.LP
Types:

.RS 3
Pt = {X::integer(), Y::integer()}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFromWindow(Window) -> integer()
.br
.RS
.LP
Types:

.RS 3
Window = wxWindow:wxWindow()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getPPI(This) -> {W::integer(), H::integer()}
.br
.RS
.LP
Types:

.RS 3
This = wxDisplay()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxDisplay()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>