.TH wxAuiTabArt 3 "wx 1.6.1" "" "Erlang Module Definition"
.SH NAME
wxAuiTabArt \- See external documentation: wxAuiTabArt.
.SH DESCRIPTION
.LP
See external documentation: wxAuiTabArt\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxAuiTabArt()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
setFlags(This, Flags) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Flags = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMeasuringFont(This, Font) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Font = wxFont() (see module wxFont)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setNormalFont(This, Font) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Font = wxFont() (see module wxFont)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setSelectedFont(This, Font) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Font = wxFont() (see module wxFont)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, Colour) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Colour = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setActiveColour(This, Colour) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxAuiTabArt()
.br
Colour = wx_colour() (see module wx)
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>