.TH Observer 7 "observer 2.3.1" "Ericsson AB" "Erlang Application Definition"
.SH NAME
Observer \- The Observer Application
.SH DESCRIPTION
.LP
The Observer application contains tools for tracing and investigation of distributed systems\&.
.SH "CONFIGURATION"

.LP
No configuration parameters are available for this application\&.