.TH cdv 1 "observer 2.3.1" "Ericsson AB" "User Commands"
.SH NAME
cdv \- Script to start the Crashdump Viewer from the
  OS command line.
  
.SH DESCRIPTION
.LP
The \fIcdv\fR\& shell script is located in directory \fIpriv\fR\& of the Observer application\&. The script is used for starting the Crashdump Viewer tool from the OS command line\&.
.LP
For Windows users, \fIcdv\&.bat\fR\& is found in the same location\&.
.SH EXPORTS
.LP
.B
cdv [file]
.br
.RS
.LP
Argument \fIfile\fR\& is optional\&. If not specified, a file dialog is displayed, allowing you to select a crashdump from the file system\&.
.RE