.TH wxActivateEvent 3 "wx 1.3.3" "" "Erlang Module Definition"
.SH NAME
wxActivateEvent \- See external documentation: wxActivateEvent.
.SH DESCRIPTION
.LP
See external documentation: wxActivateEvent\&.
.RS 2
.TP 2
.B
Use \fBwxEvtHandler:connect/3\fR\& with EventType::
\fIactivate\fR\&, \fIactivate_app\fR\&, \fIhibernate\fR\&
.RE
.LP
See also the message variant \fB#wxActivate{\fR\&} event record type\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxEvent\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
\fIwxActivateEvent()\fR\&:

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getActive(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = wxActivateEvent()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>