.TH jinterface 3 "jinterface 1.11" "Ericsson AB" "Erlang Module Definition"
.SH NAME
jinterface \- A Java communication tool to Erlang.
.SH DESCRIPTION
.LP
Jinterface Java package contains java classes, which help you integrate programs written in Java with Erlang\&. The reference documentation is available only on the web in Javadoc format\&.
.LP

.RS -4
.B
Note:
.RE
By default, the \fIjinterface\fR\& library is only guaranteed to be compatible with other Erlang/OTP components from the same release as the \fIjinterface\fR\& library itself\&. See the documentation of the \fIOtpCompatRel\fR\& property in the Java API documentation\&.

.SH "SEE ALSO"

.LP
Jinterface User\&'s Guide