.TH wxGCDC 3 "wx 1.9.1" "" "Erlang Module Definition"
.SH NAME
wxGCDC \- See external documentation: wxGCDC.
.SH DESCRIPTION
.LP
See external documentation: wxGCDC\&.
.LP
This class is derived (and can use functions) from: 
.br
wxDC 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxGCDC():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> wxGCDC()
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(Dc) -> wxGCDC()
.br
.RS
.LP
Types:

.RS 3
Dc = wxWindowDC:wxWindowDC()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getGraphicsContext(This) -> wxGraphicsContext:wxGraphicsContext()
.br
.RS
.LP
Types:

.RS 3
This = wxGCDC()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setGraphicsContext(This, Ctx) -> ok
.br
.RS
.LP
Types:

.RS 3
This = wxGCDC()
.br
Ctx = wxGraphicsContext:wxGraphicsContext()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::wxGCDC()) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>