.TH observer 3 "observer 2.3.1" "Ericsson AB" "Erlang Module Definition"
.SH NAME
observer \- A GUI tool for observing an Erlang system.
.SH DESCRIPTION
.LP
Observer is a graphical tool for observing the characteristics of Erlang systems\&. The tool Observer displays system information, application supervisor trees, process information, ETS tables, Mnesia tables, and contains a front end for Erlang tracing with module \fB\fIttb\fR\&\fR\&\&.
.LP
For detalis about how to get started, see the \fB\fIUser\&'s Guide\fR\&\fR\&\&.
.SH EXPORTS
.LP
.B
start() -> ok
.br
.RS
.LP
Starts the Observer GUI\&. To stop the tool, close the window\&.
.RE