.TH wxAcceleratorTable 3 "wx 1.8" "" "Erlang Module Definition"
.SH NAME
wxAcceleratorTable \- See external documentation: wxAcceleratorTable.
.SH DESCRIPTION
.LP
See external documentation: wxAcceleratorTable\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxAcceleratorTable():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> \fBwxAcceleratorTable()\fR\&
.br
.RS
.LP
See external documentation\&.
.RE
.LP
.B
new(N, Entries) -> \fBwxAcceleratorTable()\fR\&
.br
.RS
.LP
Types:

.RS 3
N = integer()
.br
Entries = [\fBwxAcceleratorEntry:wxAcceleratorEntry()\fR\&]
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
ok(This) -> boolean()
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAcceleratorTable()\fR\&
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::\fBwxAcceleratorTable()\fR\&) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>