.TH wxAuiDockArt 3 "wx 1.8" "" "Erlang Module Definition"
.SH NAME
wxAuiDockArt \- See external documentation: wxAuiDockArt.
.SH DESCRIPTION
.LP
See external documentation: wxAuiDockArt\&.
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxAuiDockArt():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
getColour(This, Id) -> \fBwx:wx_colour4()\fR\&
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getFont(This, Id) -> \fBwxFont:wxFont()\fR\&
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
getMetric(This, Id) -> integer()
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setColour(This, Id, Colour) -> ok
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
Colour = \fBwx:wx_colour()\fR\&
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setFont(This, Id, Font) -> ok
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
Font = \fBwxFont:wxFont()\fR\&
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
setMetric(This, Id, New_val) -> ok
.br
.RS
.LP
Types:

.RS 3
This = \fBwxAuiDockArt()\fR\&
.br
Id = integer()
.br
New_val = integer()
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.SH AUTHORS
.LP

.I
<>