.TH wxClientDC 3 "wx 1.8" "" "Erlang Module Definition"
.SH NAME
wxClientDC \- See external documentation: wxClientDC.
.SH DESCRIPTION
.LP
See external documentation: wxClientDC\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxWindowDC\fR\& 
.br
\fBwxDC\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxClientDC():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new() -> \fBwxClientDC()\fR\&
.br
.RS
.LP
\fIThis function is deprecated: \fR\&deprecated function not available in wxWidgets-2\&.9 and later
.LP
See external documentation\&.
.RE
.LP
.B
new(Win) -> \fBwxClientDC()\fR\&
.br
.RS
.LP
Types:

.RS 3
Win = \fBwxWindow:wxWindow()\fR\&
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::\fBwxClientDC()\fR\&) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>