.TH wxPasswordEntryDialog 3 "wx 1.8" "" "Erlang Module Definition"
.SH NAME
wxPasswordEntryDialog \- See external documentation: wxPasswordEntryDialog.
.SH DESCRIPTION
.LP
See external documentation: wxPasswordEntryDialog\&.
.LP
This class is derived (and can use functions) from: 
.br
\fBwxTextEntryDialog\fR\& 
.br
\fBwxDialog\fR\& 
.br
\fBwxTopLevelWindow\fR\& 
.br
\fBwxWindow\fR\& 
.br
\fBwxEvtHandler\fR\& 
.SH "DATA TYPES"

.RS 2
.TP 2
.B
wxPasswordEntryDialog():

.RS 2
.LP
An object reference, The representation is internal and can be changed without notice\&. It can\&'t be used for comparsion stored on disc or distributed for use on other nodes\&.
.RE
.RE
.SH EXPORTS
.LP
.B
new(Parent, Message) -> \fBwxPasswordEntryDialog()\fR\&
.br
.RS
.LP
Types:

.RS 3
Parent = \fBwxWindow:wxWindow()\fR\&
.br
Message = \fBunicode:chardata()\fR\&
.br
.RE
.RE
.RS
.LP
Equivalent to \fBnew(Parent, Message, [])\fR\&\&.
.RE
.LP
.B
new(Parent, Message, Options::[Option]) -> \fBwxPasswordEntryDialog()\fR\&
.br
.RS
.LP
Types:

.RS 3
Parent = \fBwxWindow:wxWindow()\fR\&
.br
Message = \fBunicode:chardata()\fR\&
.br
Option = {caption, \fBunicode:chardata()\fR\&} | {value, \fBunicode:chardata()\fR\&} | {style, integer()} | {pos, {X::integer(), Y::integer()}}
.br
.RE
.RE
.RS
.LP
See external documentation\&.
.RE
.LP
.B
destroy(This::\fBwxPasswordEntryDialog()\fR\&) -> ok
.br
.RS
.LP
Destroys this object, do not use object again
.RE
.SH AUTHORS
.LP

.I
<>