.TH common_test 3 "common_test 1.19" "Ericsson AB" "Erlang Module Definition"
.SH NAME
common_test \- A framework for automated testing of any target nodes.
.SH DESCRIPTION
.LP
The \fICommon Test\fR\& framework is an environment for implementing and performing automatic and semi-automatic execution of test cases\&.
.LP
In brief, \fICommon Test\fR\& supports:
.RS 2
.TP 2
*
Automated execution of test suites (sets of test cases)
.LP
.TP 2
*
Logging of events during execution
.LP
.TP 2
*
HTML presentation of test suite results
.LP
.TP 2
*
HTML presentation of test suite code
.LP
.TP 2
*
Support functions for test suite authors
.LP
.TP 2
*
Step-by-step execution of test cases
.LP
.RE
